site:
  url: https://jakarta.ee/learn/docs/
  title: Jakarta EE Documentation
  start_page: jakartaee-tutorial:ROOT:index.adoc
  keys:
    googleAnalytics: GTM-5WLCZXC

content:
  # branches will be updated when PRs are merged
  sources:
  - url: https://github.com/jakartaee/jakartaee-tutorial.git
    start_paths:
      - src/main/antora
    branches:
      - release/9.1
      - main

urls:
  latest_version_segment: current

ui:
  output_dir: _
  bundle:
    url: https://github.com/jakartaee/jakartaee-documentation-ui/releases/download/latest/ui-bundle.zip
    snapshot: true

runtime:
  log:
    level: debug

antora:
  extensions:
  - '@antora/lunr-extension'
  - '@antora/pdf-extension'
